### ISSUE TITLE
FR: Add snippet reloading function

### ISSUE THREAD

**Issue by chrisgrieser** [garymjr/nvim-snippets#13]
I am the dev of [nvim-scissors](https://github.com/chrisgrieser/nvim-scissors), which is made for editing and creating VSCode-style snippets. It pairs very well with this plugin, even more so than Luasnip. 

The only functionality missing to make this plugin a full replacement for Luasnip would be the ability to reload snippet files during runtime. Without it, users would have to restart nvim every time they edit/create a snippet with nvim-scissors.

Luasnip has `require("luasnip.loaders").reload_file(filepath)` for this, and an equivalent for this plugin would be really useful.

**Comment by garymjr** [comment]
I added this in #16. You can use `Snippets.utils.reload_file(full_path)` or `require("snippets.utils").reload_file(full_path)`

**Comment by chrisgrieser** [comment]
fantastic, thank you!

**Comment by chrisgrieser** [comment]
A minor follow-up: could there be an option to suppress the notification when reloading? Reason being that `nvim-scissors` already notifies the user, and getting two notifications (one from nvim-scissors, one from nvim-snippets) is a bit unnecessary.
