### ISSUE TITLE
can i load ansible snippets?

### ISSUE THREAD

**Issue by mosheavni** [garymjr/nvim-snippets#15]
https://github.com/phenomenes/ansible-snippets/tree/master

i think they use the same structure as friendly snippets

**Comment by telemachus** [comment]
At a quick glance, those are in SnipMate and UltiSnips formats, which is not the same format as vscode snippets.

**Comment by garymjr** [comment]
> At a quick glance, I think no. Those seem to be in SnipMate and UltiSnips formats, but this plugin supports vscode-format snippets.

This is correct. I only intend to support vscode style snippets in this plugin
