### ISSUE TITLE
Allow duplicate key in snippets

### ISSUE THREAD

**Issue by imroc** [garymjr/nvim-snippets#18]
I use LuaSnip before, and defined my custom snippets `markdown.json`:
```json
{
  "Insert code block": {
    "prefix": "cb",
    "body": [
      "```$1",
      "$0",
      "```"
    ],
    "description": "Insert code block"
  }
}
```

Which uses the same key `Insert code block` with friendly-snippets:

```json
    "Insert code block": {
        "prefix": "codeblock",
        "body": ["```${1:language}", "$0", "```"],
        "description": "Insert fenced code block"
    },
```

Both snippets works (prefix `cb` and `codeblock`).

But when I switch to nvim-snippets, it not work any more, unless change the key name to another name that not duplicate with friendly-snipppets.

It will be better to support the snippet key name duplication.

**Comment by garymjr** [comment]
This looks like something I'd like to support. I'll need to refactor how I'm currently storing the snippets once they're parsed, so it could take a few days to get this added.

**Comment by imroc** [comment]
> This looks like something I'd like to support. I'll need to refactor how I'm currently storing the snippets once they're parsed, so it could take a few days to get this added.

Nice, looking forward to this
