### ISSUE TITLE
Cannot nested use snippets

### ISSUE THREAD

**Issue by Old-Farmer** [garymjr/nvim-snippets#25]
As title.

For example：

1. input a snippet, like func (p1(active), p2, p3)
2. input another snippet in p1, like func( func2(ip1, ip2, ip3), p2, p3)
3. then p2, p3 cannot be jumped to any more.

Is this a bug for this plugin, or it hasn't been supportted by neovim?

Thanks.

**Comment by garymjr** [comment]
I don't handle any of the actual jumping in this plugin, all of that is handled by `vim.snippet`. This should be raised to neovim core directly

**Comment by Old-Farmer** [comment]
> I don't handle any of the actual jumping in this plugin, all of that is handled by `vim.snippet`. This should be raised to neovim core directly

Got it. Thanks for your reply.
