### ISSUE TITLE
Deprecated(?)` ._snippet_grammar` member no longer available

### ISSUE THREAD

**Issue by awilkins** [garymjr/nvim-snippets#29]
Using nvim-snippets as part of LazyVim

Running into this error every time snippets are listed in completion.

```
Error executing vim.schedule lua callback: ...hare/nvim/lazy/nvim-snippets/lua/snippets/utils/init.lua:202: attempt to index field '_snippet_grammar' (a nil value)
stack traceback:
	...hare/nvim/lazy/nvim-snippets/lua/snippets/utils/init.lua:202: in function 'safe_parse'
	...hare/nvim/lazy/nvim-snippets/lua/snippets/utils/init.lua:215: in function 'expand_vars'
	...share/nvim/lazy/nvim-snippets/lua/snippets/utils/cmp.lua:79: in function 'resolve'
	...lkins/.local/share/nvim/lazy/nvim-cmp/lua/cmp/source.lua:384: in function 'resolve'
	...ilkins/.local/share/nvim/lazy/nvim-cmp/lua/cmp/entry.lua:505: in function 'resolve'
	...wilkins/.local/share/nvim/lazy/nvim-cmp/lua/cmp/view.lua:287: in function 'fn'
	.../.local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/async.lua:71: in function <.../.local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/async.lua:69>
```

**Comment by garymjr** [comment]
I've hopefully resolved this with #30. I copied the parser logic that was being used in `_snippet_grammer` locally into nvim-snippets. Let me know if the issue persists and thanks for reporting it.

**Comment by folke** [comment]
Why was this needed? As far as I can see, `vim.lsp._snippet_grammar` is still in core.
Maybe op is using an old nightly?

**Comment by garymjr** [comment]
I was hesitant to do this to begin with since I didn't want to need to maintain a separate instance of of the same grammar. I didn't want to cause a regression in LazyVim though if there was a potential that the grammar didn't exist on on 0.10. I'm going to revert this PR then as a result. Thanks for pointing this out @folke

**Comment by folke** [comment]
@garymjr  You also want to remove the `vim.print` statements in get_selected_text!! :)

**Comment by garymjr** [comment]
> @garymjr You also want to remove the `vim.print` statements in get_selected_text!! :)

Done 🤦
