### ISSUE TITLE
Bug with custom `search_paths`

### ISSUE THREAD

**Issue by dpetka2001** [garymjr/nvim-snippets#33]
After the merge of #31 a custom search paths like `search_paths = { vim.fn.stdpath("config") .. "/misc/snippets" }` causes an error
```
lazy.nvim Failed to run `config` for nvim-snippets

vim/fs.lua:0: invalid value (table) at index 2 in table for 'concat'

# stacktrace:
  - vim/fs.lua:0 _in_ **joinpath**
```

**Comment by garymjr** [comment]
I can't seem to reproduce this.

**Comment by dpetka2001** [comment]
Oh, does that PR mean we don't have to specify a `package.json` any more? I deleted the file I had previously to define the paths and the error doesn't occur now.

**Comment by garymjr** [comment]
Correct. We read the package.json for friendly-snippets. For everything else we use file/folder name to determine what language the snippets should be included.

**Comment by dpetka2001** [comment]
I see. Thank you very much for the clarification and apologies for the false alarm.
