### ISSUE TITLE
Snippets no longer filetype specific

### ISSUE THREAD

**Issue by sQVe** [garymjr/nvim-snippets#37]
Hey,

Since https://github.com/garymjr/nvim-snippets/commit/8f85fc2a27d54434a22e9d9bc71655ce632fbef0 snippets are no longer filetype specific. All snippets loaded, for multiple different filetypes, are available for all buffers.

I'm assuming that this is an unwanted behaviour?

Cheers 🍻

**Comment by garymjr** [comment]
This is fixed in #39. Thanks for pointing this out!
