### ISSUE TITLE
How to disable snippet source programmatically?

### ISSUE THREAD

**Issue by Urie96** [garymjr/nvim-snippets#42]
I want to enable snippet only when there are at least two letters before the cursor. Is is possible?
Now:
![image](https://github.com/garymjr/nvim-snippets/assets/43716456/d44b8e44-c26c-4899-b219-d788719c92e5)

**Comment by garymjr** [comment]
You can use the `keyword_length` field when setting the snippet source `{name = 'snippets', keyword_length = 2}`
