### ISSUE TITLE
cmp menu doesn't appear when typing punctuation characetrs

### ISSUE THREAD

**Issue by REmerald** [garymjr/nvim-snippets#44]
When typing special characters such as `#`, `/` or `@`, the nvim-cmp menu doesn't appear unless I type an alphabetical character afterwards.
This is problematic because I can't insert snippets with prefixes consisting entirely of these characters, e.g. `#`, `##`, `/`, `//`, `/**` in friendly-snippets `python.json`, `c.json` and `cdoc.json` respectively.
The bug was discovered in https://github.com/rafamadriz/friendly-snippets/pull/454#issuecomment-2140739466. Redirected from https://github.com/LazyVim/LazyVim/issues/3438#issuecomment-2145543963.

**Comment by garymjr** [comment]
This is fixed in 56b4052
