### ISSUE TITLE
Support for new native auto-completion

### ISSUE THREAD

**Issue by lourenci** [garymjr/nvim-snippets#45]

**Comment by garymjr** [comment]
I'm not sure builtin completion is extensible enough to support something like this right now. Nevertheless it's something I'll keep my eye on and see if the opportunity arises to support this. Closing for now though as I think it's likely more work than it's worth currently. Thanks for the suggestion though!

**Comment by lourenci** [comment]
It should be. It already supports snippets coming from the LSP server. Anyway, thanks for the plugin.

**Comment by Massolari** [comment]
I came up with something here: https://github.com/garymjr/nvim-snippets/pull/68
