### ISSUE TITLE
How can I add snippet from plugin ( ./local/share/xxx recursively ) ?

### ISSUE THREAD

**Issue by kiuKisas** [garymjr/nvim-snippets#49]
E.g, I install [solid-snippets](https://github.com/solidjs-community/solid-snippets) through `lazy.vim`,  so my snippets are in `/home/xxx/.local/share/nvim/lazy/solid-snippets/snippets`; what would be the easiest & future-proof way to add snippets installed this way ?

**Comment by garymjr** [comment]
You can use the `search_paths` option. In this case you can use `search_paths = {vim.fn.stdpath('data') .. '/lazy/solid-snippets/snippets'}`
