### ISSUE TITLE
Bug: custom snippet

### ISSUE THREAD

**Issue by rubiin** [garymjr/nvim-snippets#5]
When using custom snippet with nested folders, the plugin does not work.
I think this has to do with https://github.com/garymjr/nvim-snippets#todo
` (Undecided) Add support for friendly-snippets package.json definitions`

**Comment by chrisgrieser** [comment]
I second this. The `package.json` is used by VS Code (and by Luasnip and friendly snippets) to determine which filetype matches which file(s), basically what the `extended_filestypes` config option does. 

Implementing this would also save the plugin from requiring an option for friendly-snippets, as the path to the repo could simply be added to `search_paths`.

**Comment by rubiin** [comment]
@chrisgrieser shoutout to you . Been using some of your plugins and also taking some stuffs from your neovim configs. Great stuff

**Comment by Geobert** [comment]
Hi, 

I’m using LazyVim and it ships with `nvim-snippets`. My custom snippets are https://codeberg.org/geobert/nvim-config/src/branch/main/snippets but I can’t make them work :-/
