### ISSUE TITLE
Unable to edit snippet containing markdown comment strings

### ISSUE THREAD

**Issue by Davidyz** [garymjr/nvim-snippets#51]
Hi,

I'm trying to write a custom snippet with the following definition:
```json
"sample snip": {
    "prefix": ["sample"],
    "body": "<!-- this is a sample ${1:snip} -->$0"
  }
```
for markdown files. This entry is placed in `~/.config/nvim/snippets/markdown.json` and I know the syntax is correct because my other custom snippets work fine. However, the snippet above does not work properly. 

Specifically, when I press `<TAB>`, which should iterate over the completion items from the pop-up, the whole snippet body is filled to the buffer and the cursor is placed at `$0`, instead of ${1:snip}. I'm essentially 'forced' to choose this snip because it doesn't allow me to select the next items in the completion popup and I can't edit the text at the placeholder (`$1`). This snippet also works fine (as in I can iterate over the cmp items and modify the placeholder texts normally) if I remove the surrounding `<!--` and `-->` pair.

Edit: It appears to work fine when `cmp.select_next_item({ behavior = cmp.SelectBehavior.Select })` and breaks (cannot edit placeholders and jump to `$0` immediately) when I use `cmp.select_next_item({ behavior = cmp.SelectBehavior.Insert })`.

**Comment by garymjr** [comment]
Good to know. I would assume this is related to how cmp handles inserting text. Thanks for reporting this nonetheless.

**Comment by Davidyz** [comment]
Hi thanks for replying. Do you think I should open an issue for this at nvim-cmp?
